# Generated by Django 3.2.4 on 2022-02-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='conocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'conocimiento',
                'verbose_name_plural': 'conocimientos',
            },
        ),
        migrations.CreateModel(
            name='lengua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lengua', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'lengua',
                'verbose_name_plural': 'lenguas',
            },
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia', models.ManyToManyField(max_length=20, to='Presentacion.conocimiento')),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('CCO', models.CharField(max_length=10)),
                ('manager', models.CharField(max_length=50)),
                ('man_email', models.EmailField(max_length=254)),
                ('requerimientos', models.IntegerField()),
                ('idioma', models.ManyToManyField(to='Presentacion.lengua')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentacion.rol')),
                ('tecnologias', models.ManyToManyField(to='Presentacion.especialidad')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentacion.area')),
            ],
        ),
    ]
