# Generated by Django 4.0.2 on 2022-02-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0003_rename_vertical_descripcion_portafolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vertical',
            new_name='portafolio',
        ),
        migrations.RenameField(
            model_name='descripcion',
            old_name='portafolio',
            new_name='vertical',
        ),
    ]
