# Generated by Django 4.0.2 on 2022-02-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0004_rename_vertical_portafolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcion',
            name='foto',
            field=models.ImageField(default=1, upload_to='Presentacion/Imagenes'),
            preserve_default=False,
        ),
    ]
