# Generated by Django 4.0.2 on 2022-03-03 21:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0005_descripcion_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcion',
            name='soluciones',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Thousand Eyes', 'Thousand Eyes'), ('Intersight', 'Intersight'), ('AppDynamics', 'AppDynamics'), ('Webex', 'Webex'), ('Umbrella', 'Umbrella'), ('SD-WAN', 'SD-WAN'), ('SASE', 'SASE'), ('APIC', 'APIC'), ('IoT', 'IoT')], default=1, max_length=72),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descripcion',
            name='foto',
            field=models.ImageField(upload_to='Presentacion/static/build/images'),
        ),
        migrations.RemoveField(
            model_name='descripcion',
            name='idioma',
        ),
        migrations.AddField(
            model_name='descripcion',
            name='idioma',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Español', 'Español'), ('Inglés', 'Inglés'), ('Portugués', 'Portugués')], default=1, max_length=24),
            preserve_default=False,
        ),
    ]
