# Generated by Django 4.0.2 on 2022-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0006_descripcion_soluciones_alter_descripcion_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='foto',
            field=models.ImageField(upload_to='static/build/images'),
        ),
    ]
