# Generated by Django 4.0.2 on 2022-03-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0007_alter_descripcion_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='foto',
            field=models.ImageField(upload_to='Presentacion/static/build/images'),
        ),
    ]
