# Generated by Django 4.0.3 on 2022-03-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0008_alter_descripcion_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='foto',
            field=models.ImageField(upload_to='media/Imagenes'),
        ),
    ]
