# Generated by Django 4.0.3 on 2022-03-24 17:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0009_alter_descripcion_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='idioma',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Spanish', 'Spanish'), ('English', 'English'), ('Portuguese', 'Portuguese')], max_length=26),
        ),
    ]
