# Generated by Django 3.2.8 on 2022-04-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0010_alter_descripcion_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='foto',
            field=models.ImageField(upload_to='static/build/images'),
        ),
    ]
