# Generated by Django 3.2.8 on 2022-04-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentacion', '0013_alter_descripcion_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcion',
            name='descripcion',
            field=models.CharField(default="I'm a Cisconian!", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='descripcion',
            name='foto',
            field=models.ImageField(upload_to='media/Imagenes'),
        ),
    ]
